### ISSUE TITLE
Return value not properly formated 

### ISSUE THREAD

**Issue by menyhartszabolcs** [komape/deepl_dart#14]
Hi, 

If the return value of the object contains a utf8 character the return value is wrong formated. 

https://stackoverflow.com/questions/51101471/how-can-i-convert-string-to-utf8-in-dart

The fix is: 

In translator.dart file 
translateTextList:
    List<TextResult> textResults = TextResultResponse.fromJson(
            jsonDecode(utf8.decode(translateRes.bodyBytes)))
        .translations;

**Comment by komape** [comment]
Thanks for sharing. Can you describe how to reproduce the error? What is the expected output? What is the actual output?

**Comment by komape** [comment]
@menyhartszabolcs Do you want to create a PR fixing this issue?

**Comment by menyhartszabolcs** [comment]
If you translate "The force be with you" with the original code the sentence output will be:
SiÅa bÄdzie z tobÄ

But the translation should looks like: 
Siła będzie z tobą

The error is in the translator.dart file
TextResult result = await translator
      .translateTextSingular('The force be with you', 'PL', sourceLang: 'EN');
  print(result.text);
  
  
To fix the bug you have to change jsonDecode(translateRes.body) to jsonDecode(utf8.decode(translateRes.bodyBytes))

  List<TextResult> textResults =
        TextResultResponse.fromJson(jsonDecode(utf8.decode(translateRes.bodyBytes)))
            //utf8.decode(translateRes.bodyBytes)
            .translations;
    return textResults;

**Comment by komape** [comment]
@menyhartszabolcs Version 1.0.2 is available on pub.dev

https://pub.dev/packages/deepl_dart
