### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by takkiraz** [komape/deepl_dart#20]
I'm trying to create a simple Flutter translation app using your package.
 
Unfortunately I get 403 CORS errors when I request source languages for example.
I already checked if my API key is wrong, but when I request the same API resource with cURL I get a 200 OK.

deepl_dart version: `^1.1.0`

Console errors:

![Screenshot 2022-09-08 182352](https://user-images.githubusercontent.com/33528315/189175567-cf3bfce4-2f82-47ce-b107-30f372752f00.png)

Network:

![Screenshot 2022-09-08 182541](https://user-images.githubusercontent.com/33528315/189175610-84356cad-f52d-4d24-9668-a4e1419eda4b.png)

![Screenshot 2022-09-08 182628](https://user-images.githubusercontent.com/33528315/189175622-dbc1bd05-fe79-4a04-8c39-8253ec5ccf92.png)

**Comment by komape** [comment]
Did you try to send the same request from your website without the package?

Please have a look into [the CORS documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS):

> CORS is an [HTTP](https://developer.mozilla.org/en-US/docs/Glossary/HTTP)-header based mechanism that allows a server to indicate any [origins](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (domain, scheme, or port) other than its own from which a browser should permit loading resources.

The problems source lies in the fact that the request is sent from the browser. cURL is not a browser and also not affected by CORS. Have you checked StackOverflow, for example [this post](https://stackoverflow.com/questions/69217582/how-do-i-set-the-origin-in-the-deepl-api-on-javascript)?

**Comment by takkiraz** [comment]
Yes you're right. The problem is not dependent from the package.
I've already checked this post on SO, but it does'nt help me.
I will take a deeper look at this problem and close the issue for now since this is not related to the package.

**Comment by komape** [comment]
Let me know how you fixed it. You probably won't be the last one with that issue 😉
