### ISSUE TITLE
Add Support for Web

### ISSUE THREAD

**Issue by faizanhub** [komape/deepl_dart#21]
Hello, can you please share that is this package can be used for web also or do you have any plans for flutter web support ?

**Comment by komape** [comment]
Hi @faizanhub, so far I didn't had a chance to look deeper into this. Spontaneously, I don't see anything that would block this. I'll try to work onto this in December. Feel free to do so as well.

**Comment by komape** [comment]
@faizanhub Updated the Package to support Web. Please try it out and let me know how it goes.

**Comment by faizanhub** [comment]
@komape Yes, I will try and let you know. Thanks

**Comment by faizanhub** [comment]
The API is throwing an XMLHttp Request error. Is this coming from API or any other source?

![image](https://user-images.githubusercontent.com/38282882/205123112-5abcbc51-08d4-4057-b0a4-6d2f9f9a15d4.png)

**Comment by faizanhub** [comment]
Same code works on mobile.

**Comment by komape** [comment]
@faizanhub Do you have a reproducible?
