### ISSUE TITLE
Use JSON instead of URL encoded

### ISSUE THREAD

**Issue by NeariX67** [komape/deepl_dart#24]
When using translateTextList with 50 elements, the url gets too long to include the target language in the url, and thus the request fails. Using JSON instead of URL parameters would solve this issue.

**Comment by komape** [comment]
@NeariX67 Thanks for sharing! Do you have a code snippet to reproduce the behavior?

**Comment by komape** [comment]
@NeariX67 Please check out v1.4.0 which has been just released to [pub.dev](https://pub.dev/packages/deepl_dart).

**Comment by NeariX67** [comment]
Will do, thank you very much.
