### ISSUE TITLE
Add Support for Translation Context

### ISSUE THREAD

**Issue by HighLiuk** [komape/deepl_dart#25]
DeepL supports translation context:

https://developers.deepl.com/docs/best-practices/working-with-context

This guy added support for it > https://github.com/komape/deepl_dart/compare/master...jakobaltendorfer:deepl_dart:master

@komape please merge it.

**Comment by komape** [comment]
@HighLiuk Can you create a PR? Then I can have a look and try it out.

**Comment by HighLiuk** [comment]
I've already tried but I'm not a collaborator. I guess you can.
Unless I fork that guy's fork but credits should go to them

Il mar 1 ott 2024, 10:06 Konstantin Pelz ***@***.***> ha
scritto:

**Comment by komape** [comment]
@HighLiuk Let me see what I can do.
